// Manages raw TCP port-forwards for camera RTSP streams via an EXISTING
// nginx Docker container's stream{} block (see dashboard/lib/docker.ts for
// container lifecycle patterns this mirrors via the shell-out-to-`docker`
// convention already established in compose.ts).
//
// The nginx container is NOT owned by this dashboard — confirmed live
// against the real deployment that its nginx.conf already has a hand-written
// top-level `stream { ... }` block with real, currently-active forwards that
// predate this feature. Regenerating the whole file (rather than writing to
// a separate include path) is the only option that doesn't require a manual
// one-time migration, so this module preserves everything outside a pair of
// marker comments and only ever rewrites the content between them.
import fs from 'fs';
import os from 'os';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import { listEnvFiles, readDeviceEnv } from './env-parser';
import { readSettings } from './settings';

const execAsync = promisify(exec);

const BEGIN_MARKER = '# BEGIN DASHBOARD-MANAGED PORT FORWARDS (do not edit by hand — regenerated by the dashboard Settings/device pages)';
const END_MARKER = '# END DASHBOARD-MANAGED PORT FORWARDS';

// Ports this dashboard/stack already knows it uses — a registry-based check,
// not a live OS-level socket probe (stated plainly in the UI hint too).
const RESERVED_PORTS = new Set(['22', '3000', '3002', '5432', '5435', '1883', '8000', '8001', '8002', '8090', '8555', '8189']);

export interface PortForward {
  deviceCode: string;
  listenPort: string;
  srcIp: string;
  srcPort: string;
}

export function collectPortForwards(): PortForward[] {
  const forwards: PortForward[] = [];
  for (const code of listEnvFiles()) {
    const env = readDeviceEnv(code);
    if (!env || env.PORTFWD_ENABLED !== 'true') continue;
    if (!env.PORTFWD_LISTEN_PORT || !env.PORTFWD_SRC_IP) continue;
    forwards.push({
      deviceCode: code,
      listenPort: env.PORTFWD_LISTEN_PORT,
      srcIp: env.PORTFWD_SRC_IP,
      srcPort: env.PORTFWD_SRC_PORT || '554',
    });
  }
  return forwards;
}

// Returns a human-readable conflict reason, or null if the port is free.
export function findPortConflict(listenPort: string, excludeDeviceCode?: string): string | null {
  if (RESERVED_PORTS.has(listenPort)) {
    return `Port ${listenPort} is reserved for an existing dashboard/stack service`;
  }
  for (const fwd of collectPortForwards()) {
    if (fwd.deviceCode === excludeDeviceCode) continue;
    if (fwd.listenPort === listenPort) {
      return `Port ${listenPort} is already forwarded by device ${fwd.deviceCode}`;
    }
  }
  return null;
}

function buildManagedBlock(forwards: PortForward[]): string {
  if (forwards.length === 0) {
    return `    ${BEGIN_MARKER}\n    ${END_MARKER}`;
  }
  const servers = forwards
    .map(f => `    server {
        listen ${f.listenPort} so_keepalive=on;
        proxy_connect_timeout 2s;
        proxy_pass ${f.srcIp}:${f.srcPort};
        proxy_timeout 10m;
    }`)
    .join('\n');
  return `    ${BEGIN_MARKER}\n${servers}\n    ${END_MARKER}`;
}

// Inserts/replaces the dashboard-managed markers inside the FIRST top-level
// `stream { ... }` block found in the given nginx.conf content. Everything
// else in the file (existing hand-written forwards, http{}/events{} blocks,
// comments) is preserved byte-for-byte — only the text strictly between the
// markers (or, the first time, a spot just before the stream{} block's
// closing brace) is ever touched.
export function mergeIntoNginxConf(currentConf: string, forwards: PortForward[]): string {
  const managedBlock = buildManagedBlock(forwards);

  const beginIdx = currentConf.indexOf(BEGIN_MARKER);
  if (beginIdx !== -1) {
    const endIdx = currentConf.indexOf(END_MARKER);
    if (endIdx === -1) {
      throw new Error('nginx.conf has a dashboard BEGIN marker but no matching END marker — refusing to regenerate, fix manually first');
    }
    const before = currentConf.slice(0, beginIdx);
    const after = currentConf.slice(endIdx + END_MARKER.length);
    return `${before}${managedBlock}${after}`;
  }

  // First time: find the top-level `stream {` block and insert the managed
  // block just before its closing brace, using brace-depth tracking (not a
  // regex) since the block can contain nested server{}/braces.
  const streamMatch = currentConf.match(/^stream\s*\{/m);
  if (!streamMatch || streamMatch.index === undefined) {
    throw new Error('No top-level stream{} block found in nginx.conf — add an empty "stream {}" block to it manually first');
  }
  const openBraceIdx = currentConf.indexOf('{', streamMatch.index);
  let depth = 0;
  let closeBraceIdx = -1;
  for (let i = openBraceIdx; i < currentConf.length; i++) {
    if (currentConf[i] === '{') depth++;
    else if (currentConf[i] === '}') {
      depth--;
      if (depth === 0) {
        closeBraceIdx = i;
        break;
      }
    }
  }
  if (closeBraceIdx === -1) {
    throw new Error('Malformed nginx.conf — unbalanced braces in the stream{} block');
  }
  const before = currentConf.slice(0, closeBraceIdx);
  const after = currentConf.slice(closeBraceIdx);
  return `${before}${managedBlock}\n${after}`;
}

export interface DeployResult {
  deployed: boolean;
  error?: string;
}

// Reads the live nginx.conf from the configured container, merges in the
// current set of dashboard-managed forwards, validates the candidate with
// `nginx -t` BEFORE ever touching the live file, and only then swaps it in
// and reloads. An invalid candidate never reaches the real nginx.conf path.
export async function deployPortForwardConfig(): Promise<DeployResult> {
  const settings = readSettings();
  const containerName = settings.portForward?.nginxContainerName;
  if (!containerName) {
    return { deployed: false, error: 'nginx container name not configured in Settings' };
  }

  let currentConf: string;
  try {
    const { stdout } = await execAsync(`docker exec ${containerName} cat /etc/nginx/nginx.conf`, { timeout: 10000 });
    currentConf = stdout;
  } catch (e) {
    return { deployed: false, error: `could not read nginx.conf from container "${containerName}": ${errMessage(e)}` };
  }

  let newConf: string;
  try {
    newConf = mergeIntoNginxConf(currentConf, collectPortForwards());
  } catch (e) {
    return { deployed: false, error: errMessage(e) };
  }

  const tmpFile = path.join(os.tmpdir(), `nginx-candidate-${Date.now()}.conf`);
  fs.writeFileSync(tmpFile, newConf, 'utf-8');

  try {
    await execAsync(`docker cp "${tmpFile}" ${containerName}:/etc/nginx/nginx.conf.candidate`, { timeout: 10000 });

    try {
      await execAsync(`docker exec ${containerName} nginx -t -c /etc/nginx/nginx.conf.candidate`, { timeout: 10000 });
    } catch (e) {
      await execAsync(`docker exec ${containerName} rm -f /etc/nginx/nginx.conf.candidate`, { timeout: 5000 }).catch(() => {});
      return { deployed: false, error: `nginx -t validation failed, live config left untouched: ${errMessage(e)}` };
    }

    // nginx.conf is commonly a bind-mounted file (confirmed live against
    // env_services_nginx — mounted from /opt/services/nginx.conf on the
    // host). `cp`/`docker cp` both try to unlink+recreate the destination
    // inode, which fails on a bind mount even with -f ("File exists" from
    // BusyBox cp; "device or resource busy" from `docker cp`, confirmed
    // live testing both). Writing into the existing file via a shell
    // redirect truncates-in-place instead, which works on a bind mount the
    // same way `> file` always has.
    await execAsync(
      `docker exec -i ${containerName} sh -c 'cat > /etc/nginx/nginx.conf' < "${tmpFile}"`,
      { timeout: 10000 }
    );
    await execAsync(`docker exec ${containerName} rm -f /etc/nginx/nginx.conf.candidate`, { timeout: 5000 }).catch(() => {});
    await execAsync(`docker exec ${containerName} nginx -s reload`, { timeout: 10000 });
    return { deployed: true };
  } catch (e) {
    return { deployed: false, error: errMessage(e) };
  } finally {
    fs.unlinkSync(tmpFile);
  }
}

function errMessage(e: unknown): string {
  const err = e as { stderr?: string; message?: string };
  return err.stderr || err.message || String(e);
}
